version: "3.8"
services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - FLASK_APP=app
            - FLASK_ENV=development
        volumes:
            - .:/code
        depends_on:
            - elasticsearch
    elasticsearch:
        container_name: es-data
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        environment:
            - node.name=es-data
            - cluster.name=es-data-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"

volumes:
    es-data:
        driver: local
